import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Locale } from "@/lib/i18n/config";

export type MonthlyReportTx = {
  id: string;
  date: string;
  type: "ingreso" | "gasto";
  category: string;
  amount: number;
  method: string;
  notes?: string | null;
  localOnly?: boolean;
};

export type MonthlyPdfReportInput = {
  transactions: MonthlyReportTx[];
  month: string;
  monthLabel: string;
  scopeLabel: string;
  familyName?: string | null;
  locale?: Locale;
};

function copy(locale: Locale = "es-MX") {
  const en = locale === "en-US";
  return {
    title: en ? "Premium monthly report" : "Reporte mensual premium",
    executiveSummary: en ? "Executive summary" : "Resumen ejecutivo",
    generated: en ? "Generated" : "Generado",
    family: en ? "Family" : "Familia",
    income: en ? "Income" : "Ingresos",
    expenses: en ? "Expenses" : "Gastos",
    balance: "Balance",
    movements: en ? "Movements" : "Movimientos",
    insights: "Insights",
    topCategory: (label: string, total: string) =>
      en ? `Top spending category: ${label} (${total}).` : `Categoría con más gasto: ${label} (${total}).`,
    noTopCategory: en
      ? "There are no expenses to calculate a top category."
      : "No hay gastos registrados para calcular categoría principal.",
    topMethod: (label: string, count: number) =>
      en
        ? `Most used method: ${label} (${count} movement${count === 1 ? "" : "s"}).`
        : `Método más usado: ${label} (${count} movimiento${count === 1 ? "" : "s"}).`,
    noTopMethod: en ? "There is no dominant method yet." : "No hay método dominante todavía.",
    averageExpense: (value: string) =>
      en ? `Average expense per movement: ${value}.` : `Gasto promedio por movimiento: ${value}.`,
    alertNegative: (value: string) =>
      en ? `Alert: expenses exceed income by ${value}.` : `Alerta: tus gastos superan tus ingresos por ${value}.`,
    noFlowAlert: en
      ? "No cash-flow alert: income covers period expenses."
      : "Sin alerta de flujo: tus ingresos cubren los gastos del periodo.",
    expensesByCategory: en ? "Expenses by category" : "Gastos por categoría",
    category: en ? "Category" : "Categoría",
    total: "Total",
    expensePercent: en ? "% of expenses" : "% de gastos",
    noExpenses: en ? "No expenses" : "Sin gastos",
    date: en ? "Date" : "Fecha",
    type: en ? "Type" : "Tipo",
    method: en ? "Method" : "Método",
    amount: en ? "Amount" : "Monto",
    notes: en ? "Notes" : "Notas",
    incomeType: en ? "Income" : "Ingreso",
    expenseType: en ? "Expense" : "Gasto",
    noCategory: en ? "No category" : "Sin categoría",
    noMethod: en ? "No method" : "Sin método",
    generatedBy: en ? "Generated by RINDAY" : "Generado por RINDAY",
    page: en ? "Page" : "Página",
    noMovementsError: en ? "No movements available to generate the report." : "No hay movimientos para generar el reporte.",
    filenamePrefix: en ? "rinday-report" : "rinday-reporte",
  };
}

function formatMoney(value: number, locale: Locale = "es-MX") {
  return value.toLocaleString(locale, {
    style: "currency",
    currency: "MXN",
    maximumFractionDigits: 0,
  });
}

function formatDate(value: string, locale: Locale = "es-MX") {
  try {
    const [year, month, day] = value.split("-").map(Number);
    if (!year || !month || !day) return value;
    return new Date(year, month - 1, day).toLocaleDateString(locale, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return value;
  }
}

function truncate(value: string | null | undefined, max = 58) {
  const clean = String(value ?? "").replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  return `${clean.slice(0, max - 1).trim()}…`;
}

function sumBy<T extends string>(items: MonthlyReportTx[], key: (tx: MonthlyReportTx) => T) {
  const map = new Map<T, number>();
  for (const tx of items) {
    map.set(key(tx), (map.get(key(tx)) ?? 0) + tx.amount);
  }
  return Array.from(map.entries())
    .map(([label, total]) => ({ label, total }))
    .sort((a, b) => b.total - a.total);
}

function countBy<T extends string>(items: MonthlyReportTx[], key: (tx: MonthlyReportTx) => T) {
  const map = new Map<T, number>();
  for (const tx of items) {
    map.set(key(tx), (map.get(key(tx)) ?? 0) + 1);
  }
  return Array.from(map.entries())
    .map(([label, count]) => ({ label, count }))
    .sort((a, b) => b.count - a.count);
}

export function generateMonthlyPdfReport(input: MonthlyPdfReportInput) {
  const txs = input.transactions;
  const locale = input.locale ?? "es-MX";
  const labels = copy(locale);

  if (!txs.length) {
    throw new Error(labels.noMovementsError);
  }

  const incomes = txs.filter((tx) => tx.type === "ingreso");
  const expenses = txs.filter((tx) => tx.type === "gasto");
  const totalIncome = incomes.reduce((sum, tx) => sum + tx.amount, 0);
  const totalExpense = expenses.reduce((sum, tx) => sum + tx.amount, 0);
  const balance = totalIncome - totalExpense;
  const averageExpense = expenses.length ? totalExpense / expenses.length : 0;
  const categoryRows = sumBy(expenses, (tx) => tx.category || labels.noCategory);
  const methodRows = countBy(txs, (tx) => tx.method || labels.noMethod);
  const topCategory = categoryRows[0] ?? null;
  const topMethod = methodRows[0] ?? null;
  const generatedAt = new Date().toLocaleString(locale, {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  const slate = [15, 23, 42] as [number, number, number];
  const muted = [100, 116, 139] as [number, number, number];
  const sky = [14, 116, 217] as [number, number, number];

  doc.setFillColor(...slate);
  doc.rect(0, 0, pageWidth, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("RINDAY", marginX, 15);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(labels.title, marginX, 23);
  doc.setFontSize(10);
  doc.text(input.monthLabel, pageWidth - marginX, 15, { align: "right" });
  doc.text(input.scopeLabel, pageWidth - marginX, 23, { align: "right" });

  let y = 44;
  doc.setTextColor(...slate);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(labels.executiveSummary, marginX, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...muted);
  const contextLine = input.familyName
    ? `${labels.family}: ${input.familyName} · ${labels.generated}: ${generatedAt}`
    : `${labels.generated}: ${generatedAt}`;
  doc.text(contextLine, marginX, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    margin: { left: marginX, right: marginX },
    body: [
      [labels.income, formatMoney(totalIncome, locale)],
      [labels.expenses, formatMoney(totalExpense, locale)],
      [labels.balance, formatMoney(balance, locale)],
      [labels.movements, String(txs.length)],
    ],
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 2.2 },
    columnStyles: {
      0: { textColor: muted, fontStyle: "bold" },
      1: { halign: "right", textColor: slate, fontStyle: "bold" },
    },
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  doc.setTextColor(...slate);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(labels.insights, marginX, y);
  y += 7;

  const insights = [
    topCategory
      ? labels.topCategory(topCategory.label, formatMoney(topCategory.total, locale))
      : labels.noTopCategory,
    topMethod
      ? labels.topMethod(topMethod.label, topMethod.count)
      : labels.noTopMethod,
    labels.averageExpense(formatMoney(averageExpense, locale)),
    balance < 0
      ? labels.alertNegative(formatMoney(Math.abs(balance), locale))
      : labels.noFlowAlert,
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...slate);
  for (const insight of insights) {
    const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - marginX * 2);
    doc.text(lines, marginX, y);
    y += lines.length * 5 + 2;
  }

  y += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(labels.expensesByCategory, marginX, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    margin: { left: marginX, right: marginX },
    head: [[labels.category, labels.total, labels.expensePercent]],
    body: categoryRows.length
      ? categoryRows.map((row) => [
          row.label,
          formatMoney(row.total, locale),
          totalExpense > 0 ? `${((row.total / totalExpense) * 100).toFixed(1)}%` : "0.0%",
        ])
      : [[labels.noExpenses, formatMoney(0, locale), "0.0%"]],
    styles: { fontSize: 8.8, cellPadding: 2.2 },
    headStyles: { fillColor: slate, textColor: 255 },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
    },
    theme: "grid",
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...slate);
  doc.text(labels.movements, marginX, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    margin: { left: marginX, right: marginX },
    head: [[labels.date, labels.type, labels.category, labels.method, labels.amount, labels.notes]],
    body: txs.map((tx) => [
      formatDate(tx.date, locale),
      tx.type === "ingreso" ? labels.incomeType : labels.expenseType,
      truncate(tx.category, 22),
      truncate(tx.method, 18),
      formatMoney(tx.amount, locale),
      truncate(tx.notes, 46),
    ]),
    styles: { fontSize: 7.8, cellPadding: 1.7, overflow: "linebreak" },
    headStyles: { fillColor: sky, textColor: 255 },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 17 },
      4: { halign: "right", cellWidth: 24 },
      5: { cellWidth: 45 },
    },
    theme: "grid",
    didDrawPage: () => {
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(...muted);
      doc.text(labels.generatedBy, marginX, pageHeight - 8);
      doc.text(`${labels.page} ${doc.getNumberOfPages()}`, pageWidth - marginX, pageHeight - 8, {
        align: "right",
      });
    },
  });

  doc.save(`${labels.filenamePrefix}-${input.month}.pdf`);
}
